node {
	stage ('SCM checkout'){
		git "https://github.com/vikkyaradhya/GridProject.git"
		}
	stage ('Build'){
    	steps {
        echo 'Execute Tests'      
        bat "mvn clean install"
      }
     }
}
