pipeline {
	agent {
		node {
			label 'master'
		}
	}
	
	options {
		timestamps()
	}
	
	stages {
		stage("Checkout, Test $ Publish") {
			steps {
				git 'https://github.com/vikkyaradhya/GridProject.git'
				script {
					bat(/mvn clean install/)
				}
			}
		}
	}
}
